# Generated by Django 4.0.6 on 2023-07-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourse',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='collegeCourse',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='collegeCourse',
            field=models.ManyToManyField(related_name='collegeCourse', to='api.collegecourse'),
        ),
    ]
